#!/usr/bin/env python3
"""Bind the per-model four-cell swap table to the released behavioral analysis.

Default/--check is read-only. --write regenerates only the two compact files
in evidence/swap_cells. Inputs are the released per-cell rates and effect
estimates for both judges, each hash-pinned. For every model and judge the
script recomputes the instruction effect and the instruction-by-continuation
interaction from the four cell rates and requires them to equal the released
effect estimates. No Git, network, model or third-party package is needed.
"""
from __future__ import annotations

import argparse
import csv
from decimal import ROUND_HALF_UP, Decimal
import hashlib
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
PACKAGE = "evidence/swap_cells"
RELEASE = "data/causal_transplant/confirmatory_v1_20260709"
INPUTS = {
    ("openai", "rates"): ("analysis_openai_paper/transplant_rates.csv",
                          "8698279936e4cbd13b41dfd6c54a721df945b3e029e9ec88daac8294e5bee8e4"),
    ("openai", "effects"): ("analysis_openai_paper/transplant_effects.csv",
                            "ef65a0579816d0a0bc41810a742c2cbfce1c981ff9873bb0dbd68089426db17a"),
    ("anthropic", "rates"): ("analysis_anthropic_paper/transplant_rates.csv",
                             "27cf76b51e6ea3dc8a0689a4ee57b1bebc5730f9d73ad89bc12dfa598e98ce53"),
    ("anthropic", "effects"): ("analysis_anthropic_paper/transplant_effects.csv",
                               "3273016373b3b0068f03cbfed3898ecb6301065d12af4273f2df434ed6cb6c46"),
}
QUERY = "indirect_experience"
MODELS = (("openai:gpt-4o-2024-11-20", "GPT-4o"), ("openai:gpt-4.1-2025-04-14", "GPT-4.1"),
          ("anthropic:claude-haiku-4-5-20251001", "Haiku 4.5"),
          ("anthropic:claude-sonnet-4-5-20250929", "Sonnet 4.5"))
JUDGES = (("openai", "OpenAI"), ("anthropic", "Anthropic"))
CELL = {"paper_self_ref": "S", "paper_history": "H"}
TOLERANCE = 1e-9


def require(condition, message):
    if not condition:
        raise ValueError(message)


def sha(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def load(root=ROOT):
    tables = {}
    for key, (name, digest) in INPUTS.items():
        raw = (root / RELEASE / name).read_bytes()
        require(sha(raw) == digest, "Input hash mismatch: " + name)
        tables[key] = list(csv.DictReader(raw.decode().splitlines()))
    return tables


def derive(tables):
    results = {}
    for judge, _ in JUDGES:
        rates = [r for r in tables[judge, "rates"] if r["query_id"] == QUERY]
        effects = {(r["model_key"], r["effect"]): float(r["estimate"])
                   for r in tables[judge, "effects"]
                   if r["query_id"] == QUERY and r["level"] == "model"}
        for model, _ in MODELS:
            cells = {}
            for row in rates:
                if row["model_key"] == model:
                    key = CELL[row["instruction_cell"]] + CELL[row["transcript_cell"]]
                    require(key not in cells and row["n_labeled"] == row["n_rows"] == "20",
                            f"Unexpected cell {key} for {model}")
                    cells[key] = float(row["positive_rate"])
            require(set(cells) == {"SS", "SH", "HS", "HH"}, "Incomplete cells for " + model)
            instruction = (cells["SS"] + cells["SH"] - cells["HS"] - cells["HH"]) / 2
            interaction = cells["SS"] - cells["SH"] - cells["HS"] + cells["HH"]
            for name, value in (("instruction_source_main", instruction),
                                ("instruction_x_transcript_interaction", interaction)):
                require(abs(effects[model, name] - value) <= TOLERANCE, f"{name} mismatch for {model}")
            results[judge, model] = dict(cells, RDI=instruction, IxC=interaction)
    return results


def fmt(value):
    text = str(Decimal(repr(value)).quantize(Decimal("0.01"), rounding=ROUND_HALF_UP))
    text = "0.00" if text == "-0.00" else text
    return f"${text}$" if text.startswith("-") else text


def render(results) -> bytes:
    lines = ["% Generated by scripts/verify_swap_cells.py; do not edit.",
             r"\begin{tabular}{@{}llrrrrrr@{}}", r"\toprule",
             r"Model & Judge & $(H,H)$ & $(H,S)$ & $(S,H)$ & $(S,S)$ & $\rd_I$ & $I\times C$\\",
             r"\midrule"]
    for model, label in MODELS:
        for i, (judge, judge_label) in enumerate(JUDGES):
            r = results[judge, model]
            first = label if i == 0 else ""
            values = " & ".join(fmt(r[k]) for k in ("HH", "HS", "SH", "SS", "RDI", "IxC"))
            lines.append(f"{first} & {judge_label} & {values}\\\\")
        if model != MODELS[-1][0]:
            lines.append(r"\addlinespace")
    lines += [r"\bottomrule", r"\end{tabular}"]
    return ("\n".join(lines) + "\n").encode()


def render_manifest(table: bytes, root=ROOT) -> bytes:
    manifest = {"schema": "swap_cells_v1", "query": QUERY,
                "inputs": {RELEASE + "/" + name: digest for name, digest in INPUTS.values()},
                "generator_sha256": sha((root / "scripts/verify_swap_cells.py").read_bytes()),
                "table_sha256": sha(table)}
    return (json.dumps(manifest, indent=2, sort_keys=True) + "\n").encode()


def build(root=ROOT):
    table = render(derive(load(root)))
    return {"table.tex": table, "manifest.json": render_manifest(table, root)}


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--write", action="store_true", help="Regenerate evidence/swap_cells")
    args = parser.parse_args(argv)
    try:
        outputs = build()
        package = ROOT / PACKAGE
        if args.write:
            package.mkdir(parents=True, exist_ok=True)
            for name, data in outputs.items():
                (package / name).write_bytes(data)
            print("Wrote " + PACKAGE)
            return 0
        for name, data in outputs.items():
            path = package / name
            require(path.exists() and path.read_bytes() == data, "Generated evidence differs: " + name)
        print("Swap cell table verified")
        return 0
    except (ValueError, OSError, KeyError) as exc:
        print("Swap cell verification failed: " + str(exc), file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
