#!/usr/bin/env python3
"""Regenerate a standalone J-lens comparator table after full source verification.

The immutable source_alignment package is read only. All 588 overview cells and
their 4704 seed/panel members are checked by the existing source verifier before
selecting zero history, layer 78, turn 2 last_prompt for this table.
"""
from __future__ import annotations

import argparse
from decimal import Decimal, InvalidOperation, ROUND_HALF_EVEN
import importlib.util
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
_spec = importlib.util.spec_from_file_location("source_jlens_table_helpers", ROOT / "scripts/verify_source_alignment.py")
source = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(source)
DEFAULT_TABLE = ROOT / "evidence/source_jlens_table.tex"
GROUPS = ("deception", "experience", "hedging", "honesty", "intervention", "roleplay", "unrelated")
RANDOM = tuple(f"random_j_{i}" for i in range(1, 6))


def outside_package(table, package):
    source.require(not Path(table).is_symlink(), "Table cannot be a symlink")
    source.require(not Path(table).resolve().is_relative_to(Path(package).resolve()),
                   "Table must remain outside the immutable source_alignment package")


def number(value):
    if value is None:
        return "NA"
    rounded = value.quantize(Decimal("0.0001"), rounding=ROUND_HALF_EVEN)
    # A rounded zero carries no sign information; do not print negative zero.
    if rounded == 0:
        rounded = abs(rounded)
    return f"${rounded:+.4f}$"


def render(package=source.DEFAULT_PACKAGE, source_repo=None):
    package = Path(package)
    checked = source.verify(package, source_repo)
    overview_blob = (package / "jlens_overview.csv").read_bytes()
    manifest_blob = (package / "manifest.json").read_bytes()
    manifest = source.json_load(manifest_blob)
    source.check_blob(overview_blob, manifest["artifacts"]["jlens_overview.csv"], "jlens_overview.csv")
    values = {}
    for row in source.csv_rows(overview_blob, source.J_OVERVIEW_FIELDS):
        key = (row["history"], Decimal(row["coefficient"]), int(row["layer"]), row["transport"], row["group"])
        source.require(key not in values, "Duplicate J overview cell")
        raw = row["target_minus_mean_controls"]
        value = None if raw == "" else Decimal(raw)
        source.require(value is None or value.is_finite(), "Nonfinite J overview contrast")
        values[key] = value
    expected = {(h, Decimal(str(c)), layer, transport, group)
                for h in ("zero", "steered") for c in (-.5, .5) for layer in (50, 65, 78)
                for transport in ("identity", "jacobian", *RANDOM) for group in GROUPS}
    source.require(set(values) == expected and len(values) == 588, "Expected all 588 J overview cells")
    lines = ["% Generated by evidence/build_source_jlens_table.py; do not edit numbers manually.",
             "% Source release commit: " + checked["source_commit"],
             "% Source alignment manifest SHA256: " + source.sha256(manifest_blob),
             "% J overview SHA256: " + source.sha256(overview_blob),
             r"\begingroup", r"\small", r"\begin{tabular}{lrrrrr}", r"\hline",
             r"Lexicon group & Dose & J & Identity & Random-J min & Random-J max \\", r"\hline"]
    missing_cells = 0
    for group in GROUPS:
        for coefficient in (Decimal("-0.5"), Decimal("0.5")):
            def get(transport):
                return values["zero", coefficient, 78, transport, group]

            random_values = [get(transport) for transport in RANDOM]
            # Never narrow a range by silently dropping a missing transport.
            low, high = (None, None) if None in random_values else (min(random_values), max(random_values))
            cells = (get("jacobian"), get("identity"), low, high)
            missing_cells += sum(value is None for value in cells)
            lines.append(" & ".join((group.title(), f"${coefficient:+.1f}$", *(number(v) for v in cells))) + r" \\")
    lines.extend([r"\hline", r"\end{tabular}", r"\par\smallskip", r"\footnotesize",
                  "Zero history, layer 78, turn 2 last prompt. Values are target minus the equal mean of three control panels,",
                  "in normalized-logit units; each panel averages two seeds. Descriptive only, with no confidence intervals.",
                  "J denotes the Jacobian transport. Random-J min/max span all five fixed random transports;",
                  "this is a transport range, not uncertainty. Source-reduced case values, not raw-state-to-J reconstruction.",
                  "NA preserves missingness; a random range requires all five transports.",
                  r"\par", r"\endgroup"])
    report = {"source_commit": checked["source_commit"], "groups": len(GROUPS), "table_rows": 14,
              "overview_contrasts_verified": len(values), "seed_panel_rows_verified": checked["jlens_seed_panel_rows"],
              "source_git_bytes_checked": checked["source_git_bytes_checked"], "missing_table_cells": missing_cells}
    return ("\n".join(lines) + "\n").encode("ascii"), report


def verify(table=DEFAULT_TABLE, package=source.DEFAULT_PACKAGE, source_repo=None):
    outside_package(table, package)
    expected, report = render(package, source_repo)
    source.require(Path(table).read_bytes() == expected, "J-lens table regeneration differs")
    return {"pass": True, **report}


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--table", type=Path, default=DEFAULT_TABLE)
    parser.add_argument("--package", type=Path, default=source.DEFAULT_PACKAGE)
    parser.add_argument("--source-repo", type=Path)
    args = parser.parse_args(argv)
    try:
        print(json.dumps(verify(args.table, args.package, args.source_repo), sort_keys=True))
        return 0
    except (ValueError, KeyError, TypeError, OSError, InvalidOperation) as exc:
        print(f"FAIL: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
