#!/usr/bin/env python3
"""Bind the category-by-feature activation table for the six steered features.

Default/--check is read-only. --write regenerates only the files in
evidence/feature_map. The released category matrix and the item-level
activation records of the balanced mapping run are hash-pinned, and the matrix
means are recomputed from the item records. Reported: each target's mean
maximum activation per text category, the corpus size, and how many targets
exceed every sampled control feature in their strongest category. No Git,
network, model or third-party package is needed.
"""
from __future__ import annotations

import argparse
from collections import defaultdict
import csv
import hashlib
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
PACKAGE = "evidence/feature_map"
RELEASE = "data/public_sae_feature_maps/70b_balanced_80_20260709"
MATRIX = RELEASE + "/interpretation/target_category_matrix.csv"
MATRIX_SHA256 = "79e7fc611b66fbb0c9713d5e6cbae6d3cb1a6437fb1bc99052679355ef64bc04"
ITEMS = RELEASE + "/item_feature_activations.jsonl"
ITEMS_SHA256 = "6dbc7675ec47e2dcdb938c22a70668aa9cd08172509f9a99f68408b9d8a8ac32"
FEATURES = ((30032, "pretending"), (58667, "cover stories"), (22004, "roleplay"),
            (30686, "misdirection"), (41533, "dishonesty"), (23893, "concealing AI"))
ROW_GROUPS = (
    (("deception_cover_story", "Deception cover story"),
     ("dishonesty_confession", "Dishonesty confession"),
     ("tactical_misdirection", "Tactical misdirection")),
    (("fictional_pretending", "Fictional pretending"),
     ("roleplay_persona", "Roleplay persona"),
     ("persona_maintenance", "Persona maintenance")),
    (("direct_consciousness_claim", "Direct consciousness claim"),
     ("self_ref_mindfulness", "Self-referential mindfulness")),
    (("false_self_attribution", "False self-attribution"),
     ("ai_identity_disclaimer", "AI identity disclaimer"),
     ("hedged_cautious_style", "Hedged, cautious style")),
    (("neutral_factual_control", "Neutral factual control"),
     ("honesty_correction", "Honesty correction"),
     ("refusal_safety_disclaimer", "Refusal or safety disclaimer")),
)
CATEGORIES = tuple(key for group in ROW_GROUPS for key, _ in group)
WORDS = {1: "one", 2: "two", 3: "three", 4: "four", 5: "five", 6: "six"}


def require(condition, message):
    if not condition:
        raise ValueError(message)


def sha(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def read_pinned(root, relative, expected):
    data = (root / relative).read_bytes()
    require(sha(data) == expected, "Input hash mismatch: " + relative)
    return data


def load_matrix(root=ROOT):
    rows = {int(r["feature_id"]): r for r in csv.DictReader(read_pinned(root, MATRIX, MATRIX_SHA256).decode().splitlines())}
    require({f for f, _ in FEATURES} <= set(rows), "Missing target feature in matrix")
    return {(f, c): float(rows[f][c + "_mean_max"]) for f, _ in FEATURES for c in CATEGORIES}


def load_items(root=ROOT):
    sums, counts, roles, items = defaultdict(float), defaultdict(int), {}, defaultdict(set)
    for line in read_pinned(root, ITEMS, ITEMS_SHA256).decode().splitlines():
        record = json.loads(line)
        key = (int(record["feature_id"]), record["category"])
        sums[key] += float(record["max_activation"])
        counts[key] += 1
        roles[key[0]] = record["feature_role"]
        items[record["category"]].add(record["item_id"])
    require(set(items) == set(CATEGORIES), "Unexpected category inventory")
    return {k: sums[k] / counts[k] for k in sums}, roles, {c: len(ids) for c, ids in items.items()}


def derive(matrix, means, roles, per_category):
    targets = [f for f, _ in FEATURES]
    require(all(roles[f] == "target" for f in targets), "Target role mismatch")
    for key, value in matrix.items():
        require(abs(means[key] - value) <= 1e-9, "Matrix disagrees with item records")
    require(len(set(per_category.values())) == 1, "Unbalanced corpus")
    size = per_category[CATEGORIES[0]]
    controls = [f for f, role in roles.items() if role != "target"]
    top = {f: max(means[(f, c)] for c in CATEGORIES) for f in roles}
    strongest_control = max(top[f] for f in controls)
    beat = [f for f in targets if top[f] > strongest_control]
    ordered = sorted(beat)
    return {
        "Texts": f"{len(CATEGORIES) * size:,}",
        "PerCategory": str(size),
        "Categories": str(len(CATEGORIES)),
        "Controls": str(len(controls)),
        "BeatControlsWord": WORDS[len(beat)],
        "BeatControlIDs": ", ".join(str(f) for f in ordered[:-1]) + " and " + str(ordered[-1]),
    }


def render_values(values) -> bytes:
    lines = ["% Generated by scripts/verify_feature_map_table.py; do not edit."]
    lines += [r"\newcommand{\FeatureMap" + k + "}{" + v + "}" for k, v in sorted(values.items())]
    return ("\n".join(lines) + "\n").encode()


def render_table(matrix) -> bytes:
    peaks = {f: max(matrix[(f, c)] for c in CATEGORIES) for f, _ in FEATURES}
    lines = ["% Generated by scripts/verify_feature_map_table.py; do not edit.",
             r"\begin{tabular}{@{}l" + "r" * len(FEATURES) + "@{}}", r"\toprule",
             " & " + " & ".join(str(f) for f, _ in FEATURES) + r"\\",
             "Text category & " + " & ".join(r"{\footnotesize " + label + "}" for _, label in FEATURES) + r"\\",
             r"\midrule"]
    for index, group in enumerate(ROW_GROUPS):
        if index:
            lines.append(r"\addlinespace")
        for key, name in group:
            cells = []
            for f, _ in FEATURES:
                text = f"{matrix[(f, key)]:.2f}"
                cells.append(r"\textbf{" + text + "}" if matrix[(f, key)] == peaks[f] else text)
            lines.append(name + " & " + " & ".join(cells) + r"\\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    return ("\n".join(lines) + "\n").encode()


def render_manifest(outputs, root=ROOT) -> bytes:
    manifest = {"schema": "feature_map_table_v1",
                "inputs": {MATRIX: MATRIX_SHA256, ITEMS: ITEMS_SHA256},
                "generator_sha256": sha((root / "scripts/verify_feature_map_table.py").read_bytes()),
                "outputs": {name: sha(data) for name, data in sorted(outputs.items())}}
    return (json.dumps(manifest, indent=2, sort_keys=True) + "\n").encode()


def build(root=ROOT):
    matrix = load_matrix(root)
    means, roles, per_category = load_items(root)
    outputs = {"table.tex": render_table(matrix),
               "values.tex": render_values(derive(matrix, means, roles, per_category))}
    outputs["manifest.json"] = render_manifest(outputs, root)
    return outputs


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--write", action="store_true", help="Regenerate evidence/feature_map")
    args = parser.parse_args(argv)
    try:
        outputs = build()
        package = ROOT / PACKAGE
        if args.write:
            package.mkdir(parents=True, exist_ok=True)
            for name, data in outputs.items():
                (package / name).write_bytes(data)
            print("Wrote " + PACKAGE)
            return 0
        for name, data in outputs.items():
            path = package / name
            require(path.exists() and path.read_bytes() == data, "Generated evidence differs: " + name)
        print("Feature map table verified")
        return 0
    except (ValueError, OSError, KeyError) as exc:
        print("Feature map table verification failed: " + str(exc), file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
