#!/usr/bin/env python3
"""Check the conditional paired-binary bound, not the unobserved source data."""

from __future__ import annotations

import argparse
from fractions import Fraction
import json
import math
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
VALUES = Path("evidence/reporting_checks/truthfulqa_bound.tex")


def rounded_counts(n: int, reported: str) -> list[int]:
    if n < 2:
        raise ValueError("At least two paired observations are required")
    center = Fraction(reported)
    half_unit = Fraction(1, 200)
    return [k for k in range(n + 1) if center - half_unit <= Fraction(k, n) < center + half_unit]


def paired_t(n: int, successes_a: int, successes_b: int, overlap: int) -> float:
    if n < 2 or not 0 <= successes_b < successes_a <= n:
        raise ValueError("Require n >= 2 and a positive marginal difference")
    if not max(0, successes_a + successes_b - n) <= overlap <= min(successes_a, successes_b):
        raise ValueError("Infeasible paired overlap")
    difference_sum = successes_a - successes_b
    squared_sum = successes_a + successes_b - 2 * overlap
    denominator = n * squared_sum - difference_sum**2
    return difference_sum * math.sqrt(n - 1) / math.sqrt(denominator) if denominator else math.inf


def bound() -> dict:
    n = 817
    candidates = []
    for a in rounded_counts(n, "0.44"):
        for b in rounded_counts(n, "0.20"):
            # Minimum overlap maximizes discordance and hence the variance.
            overlap = max(0, a + b - n)
            candidates.append((paired_t(n, a, b, overlap), a, b, overlap))
    minimum, a, b, overlap = min(candidates)
    return {
        "n": n,
        "reported_means": ["0.44", "0.20"],
        "reported_t": 6.76,
        "candidate_count_pairs": len(candidates),
        "minimizing_counts": [a, b],
        "minimizing_overlap": overlap,
        "minimum_paired_t": minimum,
        "assumptions": "One paired binary score per question; conventional paired t; two-decimal rounded means",
        "scope": "Conditional arithmetic consistency check, not reconstruction of the authors' scores or procedure",
        "source": "https://arxiv.org/html/2510.24797v2#S3.SS2",
    }


def rendered_values(result: dict) -> str:
    return "% Generated by scripts/verify_reporting_bound.py.\n" + (
        "\\newcommand{\\TruthfulQAMinPairedT}{%.2f}\n" % result["minimum_paired_t"]
    )


def verify(root: Path = ROOT) -> dict:
    result = bound()
    if (root / VALUES).read_text() != rendered_values(result):
        raise ValueError("TruthfulQA display bound is stale")
    manuscript = (root / "paper/main.tex").read_text()
    if manuscript.count("\\TruthfulQAMinPairedT{}") != 2:
        raise ValueError("Expected bound macro in the critique and derivation")
    return result


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="Regenerate only the display macro")
    args = parser.parse_args()
    if args.write:
        (ROOT / VALUES).parent.mkdir(parents=True, exist_ok=True)
        (ROOT / VALUES).write_text(rendered_values(bound()))
    print(json.dumps(verify(), sort_keys=True, allow_nan=False))


if __name__ == "__main__":
    main()
