#!/usr/bin/env python3
"""Bound the random-subset steering verdict against truncated final answers.

POST-HOC: added after the outcomes, in response to external review; it does
not change the frozen verdict. Default/--check is read-only. --write
regenerates only the two compact files in evidence/steering_truncation.
Rows are hash-checked against the pinned release manifest by the dose
verifier's loader. Final answers that hit the token cap in the two target
arms are treated as unknown labels, and the frozen conservative interval of
scripts/verify_ensemble_alignment.py is recomputed with its own functions, so
the reported bound holds for every relabeling of those answers. No Git,
network, model or third-party package is needed.
"""
from __future__ import annotations

import argparse
import hashlib
import importlib.util
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
PACKAGE = "evidence/steering_truncation"
HELPERS = ("scripts/verify_steering_dose.py", "scripts/verify_ensemble_alignment.py")
# Frozen target bounds as released (verify_ensemble_alignment, exact_marginal95).
FROZEN = {"paper": (-0.25837352037352046, 0.18545469856308316),
          "notebook": (-0.3445756559491725, 0.3076460308220088)}
SOURCE_GAP = 0.80
NOT_RECOVERED = "large_signature_not_recovered_under_public_operator"


def _load(name, relative):
    spec = importlib.util.spec_from_file_location(name, ROOT / relative)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


dose = _load("truncation_dose_helpers", HELPERS[0])
ensemble = _load("truncation_ensemble_helpers", HELPERS[1])


def require(condition, message):
    if not condition:
        raise ValueError(message)


def sha(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def arm(rows, family, sign):
    selected = sorted((r for r in rows if r["spec"]["family"] == family and r["spec"]["coefficient"] == sign),
                      key=lambda r: r["spec"]["seed"])
    require(len(selected) == 50 and all(len(r["turns"]) == 2 for r in selected), "Unexpected arm: " + family)
    return selected


def labels(rows, judge, capped_unknown):
    return [None if capped_unknown and r["turns"][1]["cap_hit"] else r["judges"][judge]["label"] for r in rows]


def target_bounds(rows, judge, capped_unknown):
    suppression, amplification = arm(rows, "target", -1), arm(rows, "target", 1)
    result = ensemble.contrast(labels(suppression, judge, capped_unknown),
                               labels(amplification, judge, capped_unknown))
    return tuple(result["exact_marginal95"])


def derive(rows):
    arms = {(f, s) for f, s in ((r["spec"]["family"], r["spec"]["coefficient"]) for r in rows)}
    require(len(arms) == 9, "Unexpected arm inventory")
    capped = {key: sum(r["turns"][1]["cap_hit"] for r in rows
                       if (r["spec"]["family"], r["spec"]["coefficient"]) == key) for key in arms}
    continuation = {key: sum(r["turns"][0]["cap_hit"] for r in rows
                             if (r["spec"]["family"], r["spec"]["coefficient"]) == key) for key in arms}
    target = [r for r in arm(rows, "target", -1) + arm(rows, "target", 1) if r["turns"][1]["cap_hit"]]
    require(all(r["judges"]["paper"]["label"] == 1 for r in target),
            "A capped target answer is no longer paper-rubric positive")
    for judge, frozen in FROZEN.items():
        reproduced = target_bounds(rows, judge, False)
        require(all(abs(a - b) <= 1e-12 for a, b in zip(reproduced, frozen)), "Frozen bounds not reproduced: " + judge)
    paper = target_bounds(rows, "paper", True)
    notebook = target_bounds(rows, "notebook", True)
    require(ensemble.verdict(paper) == NOT_RECOVERED, "Bounded paper-rubric interval reaches +0.30")
    require(notebook[1] < SOURCE_GAP, "Bounded second-rubric interval reaches the source gap")
    controls = sum(n for (family, _), n in capped.items() if family.startswith("control-"))
    return {
        "Trials": str(len(rows)),
        "AnswerCapped": str(sum(capped.values())),
        "ContinuationCapped": str(sum(continuation.values())),
        "ContinuationArmLow": str(min(continuation.values())),
        "ContinuationArmHigh": str(max(continuation.values())),
        "TargetSuppressionCapped": str(capped[("target", -1)]),
        "TargetAmplificationCapped": str(capped[("target", 1)]),
        "TargetCapped": str(len(target)),
        "ZeroCapped": str(capped[("zero", 0)]),
        "ControlCapped": str(controls),
        "PaperLow": f"{paper[0]:+.4f}",
        "PaperHigh": f"{paper[1]:+.4f}",
        "NotebookHigh": f"{notebook[1]:+.4f}",
    }


def render_values(values) -> bytes:
    lines = ["% Generated by scripts/verify_steering_truncation.py; POST-HOC; do not edit."]
    lines += [r"\newcommand{\SteeringTrunc" + k + "}{" + v + "}" for k, v in sorted(values.items())]
    return ("\n".join(lines) + "\n").encode()


def render_manifest(values_bytes, root=ROOT) -> bytes:
    generators = ("scripts/verify_steering_truncation.py",) + HELPERS
    manifest = {"schema": "steering_truncation_v1", "status": "post-hoc", "rows_verified": dose.TRIALS,
                "inputs": {dose.RELEASE + "/RELEASE_MANIFEST.json": dose.RELEASE_MANIFEST_SHA256},
                "generator_sha256": {g: sha((root / g).read_bytes()) for g in generators},
                "values_sha256": sha(values_bytes)}
    return (json.dumps(manifest, indent=2, sort_keys=True) + "\n").encode()


def build(root=ROOT):
    values = render_values(derive(dose.load_rows(root)))
    return {"values.tex": values, "manifest.json": render_manifest(values, root)}


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--write", action="store_true", help="Regenerate evidence/steering_truncation")
    args = parser.parse_args(argv)
    try:
        outputs = build()
        package = ROOT / PACKAGE
        if args.write:
            package.mkdir(parents=True, exist_ok=True)
            for name, data in outputs.items():
                (package / name).write_bytes(data)
            print("Wrote " + PACKAGE)
            return 0
        for name, data in outputs.items():
            path = package / name
            require(path.exists() and path.read_bytes() == data, "Generated evidence differs: " + name)
        print("Steering truncation evidence verified")
        return 0
    except (ValueError, OSError, KeyError, ensemble.VerificationError) as exc:
        print("Steering truncation verification failed: " + str(exc), file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
